# Generated by Django 5.2.7 on 2026-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(max_length=6, null=True),
        ),
    ]
