# Generated by Django 5.2.7 on 2026-05-06 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_user_confirmation_code_confirmationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('theme', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('is_shown', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank', models.DateField(blank=True, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='')),
                ('avatar', models.ImageField(upload_to='')),
                ('pseudonym', models.CharField(max_length=50)),
                ('is_image_signature', models.BooleanField()),
                ('is_text_signature', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
