# Generated by Django 5.2.7 on 2026-05-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='compresed_image',
            new_name='compressed_image',
        ),
    ]
